### ISSUE TITLE
Will this module be supported?

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/cookiebot#2]
Hello these days I had more time to thinker around the shops and I looked into this module.

Are there some plans for it or it's dead in the water?

I tried installing it, configured my account but the site 'never loads', the loading icon on the tab never goes away and the website is very unresponsive, plus no cookies notification, etc.

So I reverted back to the native module.

**Comment by getdatakick** [comment]
Module is supported.

Works properly for me on my testing environment:

![image](https://user-images.githubusercontent.com/34651851/204042766-3a4469e7-6467-452f-8801-eba489d08f54.png)

There is a known problem with _Move JavaScript to the end_ functionality that have negative impact on this module. 

That's not an issue with this module, though, but problem with thirty bees core itself. See thirtybees/thirtybees#1233

**Comment by therampagerado** [comment]
Thank you!

Helpfull as always!

Will dive deeper to see what's causing my issues.
